In [7]:
import numpy as np

Question 1

In [8]:
arr1 = np.array([5, 10, 15, 20, 25])

add_arr = arr1 + 2

mul_arr = arr1 * 3

div_arr = arr1 / 2

print("Addition:", add_arr)
print("Multiplication:", mul_arr)
print("Division:", div_arr)

Addition: [ 7 12 17 22 27]
Multiplication: [15 30 45 60 75]
Division: [ 2.5  5.   7.5 10.  12.5]


Question 2

In [9]:
arr2 = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr2[::-1]
print("Reversed Array:", reversed_arr)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)

most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)

print("Most Frequent in x:", most_frequent_x, "at indices:", indices_x[0])
print("Most Frequent in y:", most_frequent_y, "at indices:", indices_y[0])

Reversed Array: [5 4 6 3 2 1]
Most Frequent in x: 1 at indices: [0 5 7 8 9]
Most Frequent in y: 1 at indices: [0 1 2]


Question 3


In [10]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

element_1_2 = arr3[0, 1]

element_3_1 = arr3[2, 0]

print("Element at (1st row, 2nd column):", element_1_2)
print("Element at (3rd row, 1st column):", element_3_1)

Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


Question 4

In [11]:
name_array = np.linspace(10, 100, 25)

print("Dimensions:", name_array.ndim)
print("Shape:", name_array.shape)
print("Total Elements:", name_array.size)
print("Data Type:", name_array.dtype)
print("Bytes Consumed:", name_array.nbytes)

reshaped_array = name_array.reshape(5, 5).T
print("Reshaped Transposed Array:\n", reshaped_array)

print("Transpose using .T:\n", name_array.reshape(5, 5).T)

Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Reshaped Transposed Array:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Transpose using .T:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


Question 5

In [12]:
ucs420_name = np.array([[10, 20, 30, 40], 
                        [50, 60, 70, 80], 
                        [90, 15, 20, 35]])

mean_value = np.mean(ucs420_name)
median_value = np.median(ucs420_name)
max_value = np.max(ucs420_name)
min_value = np.min(ucs420_name)
unique_values = np.unique(ucs420_name)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_values)

reshaped_ucs420 = ucs420_name.reshape(4, 3)
resized_ucs420 = ucs420_name[:2, :3]

print("Reshaped Array (4x3):\n", reshaped_ucs420)
print("Resized Array (2x3):\n", resized_ucs420)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [50 60 70]]
